# Generated by Django 3.2.7 on 2022-11-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TyreTypes',
            fields=[
                ('type_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tyres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('type', 'size')},
            },
        ),
    ]
