# Generated by Django 3.2.7 on 2022-11-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('ordercount', models.IntegerField()),
                ('orderamount_received', models.FloatField()),
                ('orderamount_remaining', models.FloatField()),
            ],
            options={
                'unique_together': {('email', 'phone')},
            },
        ),
    ]
