# Generated by Django 3.2.7 on 2022-11-23 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_client_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyres',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('order_amount', models.FloatField()),
                ('Client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merchant.client')),
            ],
        ),
        migrations.CreateModel(
            name='order_items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('amount', models.FloatField()),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merchant.tyres')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merchant.orders')),
            ],
        ),
    ]
