# Generated by Django 3.2.7 on 2022-11-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0006_alter_orders_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amount_paid',
        ),
    ]
