# Generated by Django 3.2.7 on 2022-11-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0007_remove_orders_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount_paid',
            field=models.FloatField(default=0.0),
        ),
    ]
