# Generated by Django 3.2.7 on 2022-11-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0009_auto_20221123_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount_paid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_date',
            field=models.DateField(default='2022-11-23'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
