# Generated by Django 3.2.7 on 2022-11-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0010_auto_20221123_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_type',
        ),
    ]
